###############################################################################
# Example configuration for the R108 nodule transcriptome pipeline
# Copy to  configs/paths.yaml  and edit the ABSOLUTE paths to fit your system.

###############################################################################
#HIGHER BASE DIRECTORIES
proj_root: /ABS/PATH/TO/Pipeline_directory
fastq_dir: /ABS/PATH/TO/Pipeline_directory/raw_data # contains A1_R1_001.fastq.gz etc.
reference: /ABS/PATH/TO/Pipeline_directory/reference
results: /ABS/PATH/TO/Pipeline_directory/results
filtering: /ABS/PATH/TO/Pipeline_directory/filtering

###############################################################################
#Trimmomatic adaptor file path
trimmomatic: /ABS/PATH/TO/tools/Trimmomatic-0.39/trimmomatic-0.39.jar
adaptors: /ABS/PATH/TO/tools/Trimmomatic-0.39

###############################################################################
#GENOME FILES IN REFERENCE DIRECTORY
genome: MedtrR108_HiC.genome.fasta
annotation: MtrunR108_HiC.1.0.gtf
splice_sites: SpliceSites_MtrunR108_HiC.1.0.txt
exons: Exons_MtrunR108_HiC.1.0.txt
hisat_index: hisat_index/MtrunR108_HiC_index

###############################################################################
#OUTPUT GTF's
merged_gtf_pre_filtering: R108_merged_nodule.gtf

###############################################################################
#CPU RESOURCES FOR EACH TASK
#Change for specific resource availability on your system
threads_fastqc: 20
threads_trimmomatic: 20
threads_hisat_index: 20
threads_hisat_quant: 20
threads_samtools: 20 
threads_stringtie: 20 
